# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-18 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MottoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=255, verbose_name='作者')),
                ('content', models.TextField(max_length=200, verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '每日一句',
                'verbose_name_plural': '每日一句',
            },
        ),
    ]
