# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-13 11:17
from __future__ import unicode_literals

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
    ]
