# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
