# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180812_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='banner_image',
            field=models.ImageField(height_field=200, null=True, upload_to='upload/', verbose_name='轮播图', width_field=820),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(height_field=150, null=True, upload_to='upload/', verbose_name='图片', width_field=220),
        ),
    ]
