# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180812_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='轮播图(820*200)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='图片(220*150)'),
        ),
    ]
