# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180812_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
