# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180812_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='图(820*200)'),
        ),
    ]
