class ErrorCode:
	"""错误码"""
	OK = "OK"
	PARAMERR = "参数错误"
	MOBILETYPEERR = "手机号格式错误"
	SERERR = "用户不存在/未注册"
	PASSWORDERR = "密码错误"
	DBERR = "数据库查询错误"
	MOBILEEXIST = "手机号已注册"
	PASSCHECKERR = "两次密码不一致"
	SMSCODEERRR = "验证码过期或无效"
	SMSCODECHECKERRR = "验证码错误"
	DATAERR = "数据库错误/异常"
	MOBILENONEERR = "手机号未填写"
	REQERR = "请求过于频繁"
	SENDSUCCESSERR = "短信验证码已发送"
	COMMENTNONEERR = "评论内容不能为空"
	USERNOLOGIN = "请登录!"
	USERNAMEERR = '用户名已注册'
