# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-15 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon', verbose_name='头像(36*36)'),
        ),
    ]
