# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='楼层'),
        ),
    ]
